"""add rank and day_change columns to Portfolio

Revision ID: 5313783cc532
Revises: 6466eeeff4b4
Create Date: 2024-06-28 18:25:41.704817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5313783cc532'
down_revision = '6466eeeff4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_change', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('daily_rank')
        batch_op.drop_column('overall_rank')
        batch_op.drop_column('day_change')

    # ### end Alembic commands ###
