"""add order table

Revision ID: 635634994b6e
Revises: 5313783cc532
Create Date: 2024-08-14 17:31:53.977195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635634994b6e'
down_revision = '5313783cc532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=100), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_status', sa.String(length=10), nullable=False),
    sa.Column('order_expiration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
