"""add order table

Revision ID: 959a61e135f9
Revises: 5313783cc532
Create Date: 2024-08-14 15:15:27.899692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959a61e135f9'
down_revision = '5313783cc532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=100), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_status', sa.String(length=10), nullable=False),
    sa.Column('order_expiration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('day_change')
        batch_op.drop_column('overall_rank')
        batch_op.drop_column('daily_rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_rank', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('overall_rank', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('day_change', sa.FLOAT(), nullable=True))

    op.drop_table('order')
    # ### end Alembic commands ###
